/* Autogenerated code, forces testlib to return exit codes for EJUDGE. */
#define EJUDGE

#include "testlib.h"
#include <stdio.h>

int main(int argc, char * argv[])
{
    //setName("compare two signed int%d's", 8 * sizeof(int));
    registerTestlibCmd(argc, argv);
    
    int n = inf.readInt();
    //int m = ouf.readInt();
    
    int a[405][405];
    for (int i = 1; i <= n; i++){
    	for (int j = 1; j <= n; j++){
    		a[i][j] = ans.readInt();	
    	}
    }
	for (int i = 1; i <= n; i++){
		int k = 0;
		for (int j = 1; j <= n; j++){
			if (a[i][j] > 0)k++;
		}
		if (k!=3)quitf(_wa,"LOH");
	}
	for (int i = 1; i <= n; i++){
		int k = 0;
		for (int j = 1; j <= n; j++){
			if (a[j][i]  > 0)k++;
		}
		if (k!=3)quitf(_wa, "LOH");
	}
	quitf(_ok,"Good job");
    /*if (ja != pa)
        quitf(_wa, "expected %d, found %d", ja, pa);
    
    quitf(_ok, "answer is %d", ja);
	*/
}
